# Generated by Django 4.0.5 on 2022-06-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lasst_name',
            new_name='last_name',
        ),
    ]
